main:
  push:
    - imports: https://cnb.cool/qujingcc/qujing-secrets/-/blob/main/envs.yml
      stages:
        - name: Build
          image: oven/bun:latest
          script: |
            bun install
            bun run build

        - name: Deploy to EdgeOne Pages
          image: node:20
          script: npx edgeone pages deploy ./out -n qujingcc-blog -t $EDGEONE_API_TOKEN
